In [1]:
import pandas as pd
import sqlite3

In [1]:
conn = sqlite3.connect("../database/superstore.db")

print("Database Created Successfully")

NameError: name 'sqlite3' is not defined

In [2]:
df = pd.read_csv("../data/processed/WA_Fn-UseC_-Telco-Customer-Churn_Cleaned.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
import sqlite3

connection = sqlite3.connect("../customer_churn.db")

In [4]:
import pandas as pd

df = pd.read_csv("../data/processed/WA_Fn-UseC_-Telco-Customer-Churn_Cleaned.csv")

df.to_sql(
    "customer_churn",
    connection,
    if_exists="replace",
    index=False
)

7043

In [7]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [8]:
df.to_sql(
    "customer_churn",
    connection,
    if_exists="replace",
    index=False
)

7043

In [9]:
connection = sqlite3.connect("../customer_churn.db")

In [10]:
query = "SELECT * FROM customer_churn LIMIT 5"

result = pd.read_sql(query, connection)

result

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [11]:
query = """
SELECT customerID,
       gender,
       MonthlyCharges
FROM customer_churn;
"""

pd.read_sql(query, connection)

      customerID  gender  MonthlyCharges
0     7590-VHVEG  Female           29.85
1     5575-GNVDE    Male           56.95
2     3668-QPYBK    Male           53.85
3     7795-CFOCW    Male           42.30
4     9237-HQITU  Female           70.70
...          ...     ...             ...
7038  6840-RESVB    Male           84.80
7039  2234-XADUH  Female          103.20
7040  4801-JZAZL  Female           29.60
7041  8361-LTMKD    Male           74.40
7042  3186-AJIEK    Male          105.65

[7043 rows x 3 columns]

In [14]:
query = """
SELECT customerID,
       MonthlyCharges
FROM customer_churn;
"""

result = pd.read_sql(query, connection)

result

      customerID  MonthlyCharges
0     7590-VHVEG           29.85
1     5575-GNVDE           56.95
2     3668-QPYBK           53.85
3     7795-CFOCW           42.30
4     9237-HQITU           70.70
...          ...             ...
7038  6840-RESVB           84.80
7039  2234-XADUH          103.20
7040  4801-JZAZL           29.60
7041  8361-LTMKD           74.40
7042  3186-AJIEK          105.65

[7043 rows x 2 columns]

In [15]:
query = """
SELECT *
FROM customer_churn
WHERE Churn='Yes';
"""

pd.read_sql(query, connection)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
1,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
2,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
3,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
4,0280-XJGEX,Male,0,No,No,49,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1864,1699-HPSBG,Male,0,No,No,12,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,Yes,Electronic check,59.80,727.80,Yes
1865,8775-CEBBJ,Female,0,No,No,9,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),44.20,403.35,Yes
1866,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
1867,0639-TSIQW,Female,0,No,No,67,Yes,Yes,Fiber optic,Yes,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
1868,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes

In [16]:
query = """
SELECT COUNT(*) AS Total_Customers
FROM customer_churn;
"""

pd.read_sql(query, connection)

   Total_Customers
0             7043

In [17]:
query = """
SELECT AVG(MonthlyCharges) AS Average_Monthly_Charge
FROM customer_churn;
"""

pd.read_sql(query, connection)

   Average_Monthly_Charge
0               64.761692

In [18]:
query = """
SELECT Contract,
       COUNT(*) AS Customers
FROM customer_churn
GROUP BY Contract;
"""

pd.read_sql(query, connection)

         Contract  Customers
0  Month-to-month       3875
1        One year       1473
2        Two year       1695